---

- hosts: all
  become: true
  tasks:

  - name: install basic packages on Ubuntu
    package:
      name:
        - nginx
        - sysbench
        - htop
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install basic packages on CentOS
    package:
      name:
        - nginx
        - epel-release
        - sysbench
        - htop
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"



