---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu, Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]


- hosts: web_servers
  become: true
  tasks:

  - name: install webserver on Ubuntu
    package:
      name:
        - nginx
        - sysbench
        - htop
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install webserver on CentOS
    package:
      name:
        - nginx
        - epel-release
        - sysbench
        - htop
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu, Debian)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest

